/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.css",
  ],
  safelist: [
    'ai-lake-gradient',
    'neural-pattern',
    'digital-mist',
    'digital-wave-bg',
    'cyber-sunrise',
    'ai-water-blur',
    'ai-insight-panel',
    'ai-glow-text',
    'ai-hover-effect',
    'ai-assistant-float',
    'holographic-button',
    'animate-neural',
    'animate-digital-flow',
    'animate-mind-wave',
    'animate-holographic',
    'animate-data-stream',
    'animate-ai-pulse',
    'animate-ripple',
    'animate-mist',
    'animate-sunrise',
    'animate-shimmer',
    'animate-float',
    'animate-wave',
    'animate-pulse-glow',
    'premium-lake-gradient',
    'morning-mist',
    'premium-water-blur',
    'readable-bg',
    'premium-shadow',
    'text-shadow',
    'text-shadow-strong',
    'sunrise-glow',
    'water-reflection',
    'hover-lift',
    'premium-button',
    'gradient-text',
    // Ultra AI classes
    'perspective-container',
    'quantum-grid',
    'ultra-void-gradient',
    'black-hole-vortex',
    'black-hole-event',
    'quantum-particle',
    'neon-lightning',
    'neural-wave-ultra',
    'holographic-aurora',
    'ultra-glass-morphism',
    'neon-cube-container',
    'neon-cube',
    'cube-face',
    'ultra-neon-text',
    'cyber-text',
    'nav-link-ultra',
    'ultra-neon-button',
    'text-3d-container',
    'text-3d-layer',
    'ultra-badge',
    'ultra-chrome-text',
    'ultra-gradient-text',
    'ultra-hologram-panel',
    'hologram-text',
    'ultra-pulse',
    'quantum-metric',
    'ultra-void-button',
    'ultra-reality-button',
    'quantum-wave-container',
    'quantum-wave',
    'glitch-overlay',
    'animate-vortex',
    'animate-event-horizon',
    'animate-neural-wave',
    'animate-aurora',
    'animate-cube-rotate',
    'animate-glitch',
    'animate-float-3d',
    'animate-quantum-float',
    'animate-text-warp',
    'animate-text-flow',
    'animate-counter',
    'animate-quantum-wave',
  ],
  theme: {
    extend: {
      animation: {
        'pulse': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}