/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.css",
  ],
  safelist: [
    'ai-lake-gradient',
    'neural-pattern',
    'digital-mist',
    'digital-wave-bg',
    'cyber-sunrise',
    'ai-water-blur',
    'ai-insight-panel',
    'ai-glow-text',
    'ai-hover-effect',
    'ai-assistant-float',
    'holographic-button',
    'animate-neural',
    'animate-digital-flow',
    'animate-mind-wave',
    'animate-holographic',
    'animate-data-stream',
    'animate-ai-pulse',
    'animate-ripple',
    'animate-mist',
    'animate-sunrise',
    'animate-shimmer',
    'animate-float',
    'animate-wave',
    'animate-pulse-glow',
    'premium-lake-gradient',
    'morning-mist',
    'premium-water-blur',
    'readable-bg',
    'premium-shadow',
    'text-shadow',
    'text-shadow-strong',
    'sunrise-glow',
    'water-reflection',
    'hover-lift',
    'premium-button',
    'gradient-text',
  ],
  theme: {
    extend: {
      animation: {
        'pulse': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}